### ISSUE TITLE
Add emoji support

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-slides#101]
Need to add a FOSS emoji font support as a fallback for the default theme and text entries. Is there any other than Google's Noto Emoji Color that we can use freely?

**Comment by LinuxUserGD** [comment]
e. g. https://github.com/eosrei/twemoji-color-font

**Comment by LinuxUserGD** [comment]
Disadvantage: In Godot it only shows the outline

**Comment by NathanLovato** [comment]
Ah if it can't display full emojis that's not worth it then. Thanks for the heads-up!

**Comment by HugeGameArtGD** [comment]
@NathanLovato That's the fallback mode of the font. With other fonts it could work.

**Comment by LinuxUserGD** [comment]
@NathanLovato That's the fallback mode of the font. With other fonts it could work.
