### ISSUE TITLE
in-slide code editor

### ISSUE THREAD

**Issue by j2l** [GDquest/godot-slides#104]
Hey, 
I was watching one of your video where you code from within the running slide and I can't find the slide exposing this tool in this project.
Is it implemented?

**Comment by NathanLovato** [comment]
It's the TextEdit node from Godot's built-in nodes.

**Comment by j2l** [comment]
Oh! Thanks!

**Comment by j2l** [comment]
Salut @NathanLovato , 
Je rebascule à l'anglais pour tout le monde.

I have a few additional questions about TextEdit, maybe I missed the documentation. Feel free to point me to it.
How to change font size of TextEdit text?
How can you switch to another slide once you're editing some text (n and p are written, not commands, whatever you do)
Can we change to markdown, instead of gdscript if wanted?

As you said, this is great tool for education and I'd love to master this one.
Thanks!

**Comment by NathanLovato** [comment]
There are no particular tools on top of Godot, to edit another slide you've got to open the corresponding scene.

Regarding fonts, they're shared resources you'll find in the `theme/fonts` folder, you need to edit these to update the font size globally in the presentation.

**Comment by j2l** [comment]
Merci.
J'étais peut-être pas super clair en anglais.

>  How to change font size of TextEdit text?

C'est la taille que je veux changer, pas la police

>  How can you switch to another slide once you're editing some text (n and p are written, not commands, whatever you do)

les touches N, P, L ne fonctionne plus dans une slide qui a TextEdit

>  Can we change to markdown, instead of gdscript if wanted?

Après coup j'ai vu rich text qui seriat bien.
