### ISSUE TITLE
Call for beautiful Pictures! Editor, new features, and games made with Godot

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-slides#33]
We need crisp and rich pictures of the editor, and of beautiful games made with Godot. Please share yours with us! 

Guidelines:

- Please upload pictures in high resolution. Ideally HD: 1920x1080, very high-quality jpeg (quality > 95) or PNG
- For the editor, please use full-screen mode (Shift F11 to toggle it on/off)
- Make sure the FileSystem tab is not too messy, same for the Inspector's state
- Make sure there are no errors in the input tab at the bottom: to clear it the console and remove errors, press `Ctrl Shift K`
- Set the font size to 18 pixels in the `Editor menu -> Editor Settings` (we can't go higher unfortunately, the layout gets messed up)

![image](https://user-images.githubusercontent.com/12694995/45461871-3cc2f600-b740-11e8-9b14-29aade9d4a39.png)

Examples:

![modern-engine](https://user-images.githubusercontent.com/12694995/45461911-709e1b80-b740-11e8-9eaa-df24ec8bc446.jpg)

![godot windows tools_2018-09-13_10-35-40](https://user-images.githubusercontent.com/12694995/45461983-cecafe80-b740-11e8-8f23-11479b1100dd.png)

**Comment by TwistedTwigleg** [comment]
I'm not sure if it will help or if the game's graphics are good enough, but I can provide pictures from [Dreams of Fire](https://twistedtwigleg.itch.io/dreams-of-fire) if you want.

I also have a real time chat project (from a tutorial I'm working on) that I can provide pictures for if you want something related to the networking side of Godot to show. Unfortunately the real time chat project not much to look at visually.

**Comment by NathanLovato** [comment]
@TwistedTwigleg thanks for the offer, but at the moment I'm really looking for pristine pictures of the editor, pictures that everyone in the community can use to promote Godot and showcase it in events and meetups. We are really lacking a decent press kit for the engine, and even the pictures on the official website could be a lot better.

I also want them to showcase features visually. For example, a professionally designed cutout character, rigged, with an animation displaying the different kinds of tracks like sprite switching and sounds in the animation editor. Or an impressive shader built with the visual shader editor. Etc.

**Comment by TwistedTwigleg** [comment]
@NathanLovato Fair enough. If in the future you change your mind and/or you see something I make and want pictures, let me know!

**Comment by NathanLovato** [comment]
Thanks for offering some help! I already get in touch with creators for them to provide me screenshots when I need them, and collect whatever I can. But this task is about creating better assets that anyone in the community can use. Including the developers, e.g. on godotengine.org

**Comment by AssjackGames** [comment]
I'll contibute some pictures using my game (linked below) when I get home from work and get the chance.
https://assjack-games.itch.io/pongslaught
