### ISSUE TITLE
Convert the tool to an add-on

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-slides#52]
If someone wants to work on this, that would be much welcome. It is not a complicated task but it would be nice to have Godot slides as a reusable add-on for people to download on the asset library.

By making an add-on we would be able to eventually add some tools in the editor to enhance the presentation design workflow. For example having a docker to create new slides with a list of widgets (a template) instance for you, and automatically saving it for you.

**Comment by texaco** [comment]
Hi,

I am not sure to fully understand what is intended in this issue.

Checking the project, the workflow seems to create scenes than inherit from other scenes.

I have been looking into Godot documentation and as far as I have found, the only way to make reusable components is by `EditorPlugin.add_custom_type` that only accept Scripts.

It is true that the doc tells scenes are quite similar to scripts I haven't found a direct way to use those scenes.

The only way that I can think is rewrite all those base scenes as GDScript.

Does anyone know any lead to follow?

**Comment by NathanLovato** [comment]
Actually, it's an old issue we should close. Since the rewrite of the presentation tool, it's much easier to use it as a standalone tool - it still needs some cleanup, but no need to make an addon from it. Inherited scenes already achieve that goal
