### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by davcri** [GDquest/godot-slides#62]
I'm starting working on the Italian translation, thanks @NathanLovato for sharing this amazing presentation!

**Comment by davcri** [comment]
I saw that there is [a PR for the German translation](https://github.com/GDquest/godot-slides/pull/61/files). I'll just wait for that to be landed before starting working on mine, just to avoid merge conflicts.

**Comment by NathanLovato** [comment]
All good, you can get going now!
