### ISSUE TITLE
Ui Controls for next and previous are switched

### ISSUE THREAD

**Issue by pwab** [GDquest/godot-slides#72]
I wondered why I couldn't switch to the **n**ext slide with `n`. It is because the controls are switched for `ui_next` and `ui_previous` as can be seen here:

![next_previous](https://user-images.githubusercontent.com/19271185/46582887-4e04d700-ca4e-11e8-9aca-e3c764b27efd.png)

**Comment by davcri** [comment]
I was wondering the same. It was like this since the initial release as far as I remember so *maybe* it's intended.

**Comment by NathanLovato** [comment]
No it's not, feel free to fix it!
