### ISSUE TITLE
Activate mouse controls by default

### ISSUE THREAD

**Issue by pwab** [GDquest/godot-slides#74]
As I am used to powerpoint and other presentation software where the mouse is the typical instrument to control the slides I would like to see mouse controls activated by default. In fact I had to read the Readme because I wasn't able to switch slides and that seems to be not very intuitive.

I know that using the arrow keys would collide with the input methods of the game you can play inside the slide about the demos (maybe switch to wasd here?). So maybe using **n** and **p** is not that bad.

My suggestion would be to at least activate the `emulate_touch_from_mouse` setting that mouse users are able to swipe with the mouse. Another possibility would be to implement mouse click actions (`lmb` next slide and `rmb` previous slide) but I'm not sure how this would affect actions like opening a website link with a click.

**Comment by NathanLovato** [comment]
There are buttons on the side of the slides now, they show on hover. You can add that no pb if you want, just gotta use unhandled_input instead of _input on the slides node
