### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by StefNik** [GDquest/godot-slides#76]

**Comment by pressundo** [comment]
I declare availability for this project.

**Comment by Mark-deMuze** [comment]
Just started on the translation into Dutch.

**Comment by NathanLovato** [comment]
@Mark-deMuze can you please open an issue to let people know that you are working on the Dutch translation?

**Comment by NathanLovato** [comment]
Hey people, any update, or should I close the issue for now?

**Comment by NathanLovato** [comment]
Closing for now as there haven't been updates. Please reopen if you want to work on this.
