### ISSUE TITLE
troubles opening csv file

### ISSUE THREAD

**Issue by dudo-k** [GDquest/godot-slides#77]
I would like to help you with traslation (to Slovak language) but have troubles with opening CSV file. Using Excel I get total mess. Any suggestion?

**Comment by Evgenij-M** [comment]
Are you using a Unicode(UTF-8) encoding? It would be nice to see a screenshot of the mess. Maybe there is a problem with delimiters.

**Comment by NathanLovato** [comment]
Open as utf-8, and with quotes as string delimiters, commas as cell delimiters

**Comment by NathanLovato** [comment]
You can use google sheets if it doesn't work with excel, or libreoffice - it works out of the box
