### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by dudo-k** [GDquest/godot-slides#81]
Here is Slovak translation. There are 2 files in ZIP: PowerPitch.csv and PowerPitch.sk.translation. Hope it's enough. Would you, please, pull it for me?
[power_pitch.zip](https://github.com/GDquest/godot-slides/files/2465041/power_pitch.zip)

**Comment by NathanLovato** [comment]
Thanks much, just added your translation. But I need your name and github email to add you as a contributor: 

![image](https://user-images.githubusercontent.com/12694995/46915079-5080a700-cfe1-11e8-89b3-862a215de257.png)

Github needs your email address to add you as a contributor.

**Comment by dudo-k** [comment]
My name: Rudolf Kovalčík
email: dudo.kovalcik@gmail.com

Thanks!
