### ISSUE TITLE
title changes when presentation starts

### ISSUE THREAD

**Issue by LinuxUserGD** [GDquest/godot-slides#85]
When I change the Script Variables Title and Subtitle in the Header, it doesn't effect the presentation itself.

Example:
![pic1](https://user-images.githubusercontent.com/34406967/46947918-9c345e80-d07c-11e8-90cc-a6cd4ce47215.png)
![pic2](https://user-images.githubusercontent.com/34406967/46947919-9c345e80-d07c-11e8-990a-21d1039c53b2.png)

**Comment by NathanLovato** [comment]
The system is trying to use the translation strings but there's no translation files registered for it. At the moment there's no code to handle presentations that you don't want to translate. Opening an issue if someone wants to add this feature, it shouldn't be too hard.

**Comment by LinuxUserGD** [comment]
#87 is closed
