### ISSUE TITLE
Add support for non-translated presentations

### ISSUE THREAD

**Issue by NathanLovato** [GDquest/godot-slides#87]
At the moment Slides assumes you'll use translations for your slides, so it'll always replace text on your slides with translation keys: unique identifiers it can use to swap the language at runtime.

For people who just want to do a quick presentation and not save the strings as CSV, Slides needs an automated solution that detects there's no translations and doesn't touch the original text. It should only call the TranslationServer node if there's translations.

## Solutions

One option is to check that next to the presentation scene's main file, there is a .CSV file with the same name.
Another option is to use the translation server on a slide/unique ID at the start of the presentation and check if it manages to replace the message (you can use `Object.tr()` for that). If not, you don't call the methods that translate the slides.

This will fix #85

**Comment by Greaby** [comment]
I created a pull request, #106, to fix this issue.
