### ISSUE TITLE
Proper text in slides not displayed, got INTRO_COLUMN_HEADER_TITLE instead

### ISSUE THREAD

**Issue by miskatonicstudio** [GDquest/godot-slides#96]
I decided to try Godot Slides for the upcoming Godot Con 2019. I added a simple slide, with a header, empty body, and a footer. When run separately the slide looks fine:

![screenshot from 2019-01-16 00-15-06](https://user-images.githubusercontent.com/36821133/51216200-cae3fe80-1923-11e9-8848-e75191ec8b64.png)

But when I run the whole presentation, it looks like this:

![screenshot from 2019-01-16 00-12-34](https://user-images.githubusercontent.com/36821133/51216126-8eb09e00-1923-11e9-9340-59581be453e3.png)

I've tried enabling the `save_as_csv` line in `Presentation.gd`, but the resulting .csv file doesn't have any content, just `id` and `en`.

**Comment by NathanLovato** [comment]
The IDs are normal, that's how we support translations: Godot translates the IDs based on the language you want to use. There's no option to have just one language at the moment - save as csv should save the EN content in the en column, then you've got to register the translation file in the project settings.
Adding an option to work without translations would take a bit of work, I don't have the time now with the KS launch in 2 days.

**Comment by miskatonicstudio** [comment]
I don't mind working with translations, i can always use any language as a second language and leave the content untranslated. The problem is that `save_as_csv` didn't actually save the content in the .csv file. I guess I can put every key in that file manually, but that's not the point, right?

**Comment by NathanLovato** [comment]
Ah I see why, it's due to changes in the way presentations work some time ago. I'll open a bug for now, see if I can find time to tackle it - but got a big workload now so it's low priority for me

**Comment by miskatonicstudio** [comment]
I wouldn't mind if you shared a quick fix :)

**Comment by NathanLovato** [comment]
It's fixed

**Comment by miskatonicstudio** [comment]
Works like a charm :wink:  Thank you for a quick response and for the great job with creating Godot Slides :+1:
