### ISSUE TITLE
slide/widgets/Picture.tscn uses a placeholder image from content/power_pitch/img/

### ISSUE THREAD

**Issue by miskatonicstudio** [GDquest/godot-slides#98]
If I understand correctly, the `slide/widgets` folder contains tools for Godot Slides, while `content` folder contains examples of presentations. One of the images (`daisy-dangerous-game-securas-1280x720.jpg`) is placed in `content`, but referenced in `slide`. I think it should be possible to safely remove the existing examples in `content` without breaking the Godot Slides functionality, so the image should be moved to e.g. `assets` (next to `cursor.png`).

This is a simple fix and I can do it myself (submit a PR), but I want to confirm first that the fix makes sense and the location for the moved image (`assets`) is correct.

**Comment by NathanLovato** [comment]
Fixed, removed the placeholder pic from the widget
